/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itheima_cpp_MainActivity */

//1.这个头文件不能删除，必须放到jni的文件夹中

#ifndef _Included_com_itheima_cpp_MainActivity
#define _Included_com_itheima_cpp_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itheima_cpp_MainActivity
 * Method:    helloCpp
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_itheima_cpp_MainActivity_helloCpp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
